// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import type { DeleteSessionData, DeleteSessionResponses, DeleteUsersIdData, DeleteUsersIdErrors, DeleteUsersIdResponses, GetSessionData, GetSessionResponses, GetUsersData, GetUsersIdData, GetUsersIdErrors, GetUsersIdResponses, GetUsersResponses, PatchUsersIdData, PatchUsersIdErrors, PatchUsersIdResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostUsersData, PostUsersErrors, PostUsersResponses } from './types.gen';
import { client } from './client.gen';
import { zDeleteSessionData, zDeleteSessionResponse, zDeleteUsersIdData, zDeleteUsersIdResponse, zGetSessionData, zGetSessionResponse, zGetUsersData, zGetUsersIdData, zGetUsersIdResponse, zGetUsersResponse, zPatchUsersIdData, zPatchUsersIdResponse, zPostAuthLoginData, zPostAuthLoginResponse, zPostUsersData, zPostUsersResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login to the BFF.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLoginData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
  requestValidator: async (data) => await zPostAuthLoginData.parseAsync(data),
  responseValidator: async (data) => await zPostAuthLoginResponse.parseAsync(data),
  url: '/auth/login',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options?.headers,
  },
});

/**
 * Delete the current user session.
 */
export const deleteSession = <ThrowOnError extends boolean = false>(options?: Options<DeleteSessionData, ThrowOnError>) => (options?.client ?? client).delete<DeleteSessionResponses, unknown, ThrowOnError>({
  requestValidator: async (data) => await zDeleteSessionData.parseAsync(data),
  responseValidator: async (data) => await zDeleteSessionResponse.parseAsync(data),
  url: '/session',
  ...options,
});

/**
 * Get public session data.
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) => (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({
  requestValidator: async (data) => await zGetSessionData.parseAsync(data),
  responseValidator: async (data) => await zGetSessionResponse.parseAsync(data),
  url: '/session',
  ...options,
});

/**
 * Get list of users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
  requestValidator: async (data) => await zGetUsersData.parseAsync(data),
  responseValidator: async (data) => await zGetUsersResponse.parseAsync(data),
  url: '/users',
  ...options,
});

/**
 * Create a new user
 */
export const postUsers = <ThrowOnError extends boolean = false>(options?: Options<PostUsersData, ThrowOnError>) => (options?.client ?? client).post<PostUsersResponses, PostUsersErrors, ThrowOnError>({
  requestValidator: async (data) => await zPostUsersData.parseAsync(data),
  responseValidator: async (data) => await zPostUsersResponse.parseAsync(data),
  url: '/users',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options?.headers,
  },
});

/**
 * Delete user by ID
 */
export const deleteUsersId = <ThrowOnError extends boolean = false>(options: Options<DeleteUsersIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteUsersIdResponses, DeleteUsersIdErrors, ThrowOnError>({
  requestValidator: async (data) => await zDeleteUsersIdData.parseAsync(data),
  responseValidator: async (data) => await zDeleteUsersIdResponse.parseAsync(data),
  url: '/users/{id}',
  ...options,
});

/**
 * Get user by ID
 */
export const getUsersId = <ThrowOnError extends boolean = false>(options: Options<GetUsersIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersIdResponses, GetUsersIdErrors, ThrowOnError>({
  requestValidator: async (data) => await zGetUsersIdData.parseAsync(data),
  responseValidator: async (data) => await zGetUsersIdResponse.parseAsync(data),
  url: '/users/{id}',
  ...options,
});

/**
 * Update user by ID
 */
export const patchUsersId = <ThrowOnError extends boolean = false>(options: Options<PatchUsersIdData, ThrowOnError>) => (options.client ?? client).patch<PatchUsersIdResponses, PatchUsersIdErrors, ThrowOnError>({
  requestValidator: async (data) => await zPatchUsersIdData.parseAsync(data),
  responseValidator: async (data) => await zPatchUsersIdResponse.parseAsync(data),
  url: '/users/{id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
});
