// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import type { DeleteSessionData, DeleteSessionResponses, DeleteUsersIdData, DeleteUsersIdErrors, DeleteUsersIdResponses, GetPaginatedUsersData, GetPaginatedUsersResponses, GetSessionData, GetSessionResponses, GetUsersByIdData, GetUsersByIdErrors, GetUsersByIdResponses, PatchUsersIdData, PatchUsersIdErrors, PatchUsersIdResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostUsersData, PostUsersErrors, PostUsersResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login to the BFF.
 */
export const postAuthLogin = <ThrowOnError extends boolean = true>(options?: Options<PostAuthLoginData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
  url: '/auth/login',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options?.headers,
  },
});

/**
 * Delete the current user session.
 */
export const deleteSession = <ThrowOnError extends boolean = true>(options?: Options<DeleteSessionData, ThrowOnError>) => (options?.client ?? client).delete<DeleteSessionResponses, unknown, ThrowOnError>({ url: '/session', ...options });

/**
 * Get public session data.
 */
export const getSession = <ThrowOnError extends boolean = true>(options?: Options<GetSessionData, ThrowOnError>) => (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({ url: '/session', ...options });

/**
 * Get list of users
 */
export const getPaginatedUsers = <ThrowOnError extends boolean = true>(options?: Options<GetPaginatedUsersData, ThrowOnError>) => (options?.client ?? client).get<GetPaginatedUsersResponses, unknown, ThrowOnError>({ url: '/users', ...options });

/**
 * Create a new user
 */
export const postUsers = <ThrowOnError extends boolean = true>(options?: Options<PostUsersData, ThrowOnError>) => (options?.client ?? client).post<PostUsersResponses, PostUsersErrors, ThrowOnError>({
  url: '/users',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options?.headers,
  },
});

/**
 * Delete user by ID
 */
export const deleteUsersId = <ThrowOnError extends boolean = true>(options: Options<DeleteUsersIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteUsersIdResponses, DeleteUsersIdErrors, ThrowOnError>({ url: '/users/{id}', ...options });

/**
 * Get user by ID
 */
export const getUsersById = <ThrowOnError extends boolean = true>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, GetUsersByIdErrors, ThrowOnError>({ url: '/users/{id}', ...options });

/**
 * Update user by ID
 */
export const patchUsersId = <ThrowOnError extends boolean = true>(options: Options<PatchUsersIdData, ThrowOnError>) => (options.client ?? client).patch<PatchUsersIdResponses, PatchUsersIdErrors, ThrowOnError>({
  url: '/users/{id}',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options.headers,
  },
});
