// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
  baseUrl: `${string}://${string}` | (string & {});
}

export interface PostAuthLoginData {
  body?: {
    email: string;
    organisation: string;
  };
  path?: never;
  query?: never;
  url: '/auth/login';
}

export interface PostAuthLoginErrors {
  /**
   * Login not authorized
   */
  401: {
    message: string;
  };
}

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export interface PostAuthLoginResponses {
  /**
   * Login Successful
   */
  200: {
    message: string;
  };
}

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export interface DeleteSessionData {
  body?: never;
  path?: never;
  query?: never;
  url: '/session';
}

export interface DeleteSessionResponses {
  /**
   * Session Deleted
   */
  200: {
    message: string;
  };
}

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export interface GetSessionData {
  body?: never;
  path?: never;
  query?: never;
  url: '/session';
}

export interface GetSessionResponses {
  /**
   * Public Session Data
   */
  200: {
    user?: {
      email: string;
      name: string;
      company: string;
      avatar?: {
        src: string;
        alt: string;
      };
    };
    [key: string]: unknown;
  };
}

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export interface GetPaginatedUsersData {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    page_size?: number;
    search?: string;
    sort?: string | Array<string>;
  };
  url: '/users';
}

export interface GetPaginatedUsersResponses {
  /**
   * List of Users
   */
  200: {
    results: Array<{
      id: number;
      name: string;
      jobTitle: string;
    }>;
    count: number;
    page: number;
    next?: string;
    previous?: string;
  };
}

export type GetPaginatedUsersResponse = GetPaginatedUsersResponses[keyof GetPaginatedUsersResponses];

export interface PostUsersData {
  body?: {
    name: string;
    jobTitle: string;
  };
  path?: never;
  query?: never;
  url: '/users';
}

export interface PostUsersErrors {
  /**
   * Invalid input
   */
  400: unknown;
}

export interface PostUsersResponses {
  /**
   * User created successfully
   */
  201: {
    id: number;
    name: string;
    jobTitle: string;
  };
}

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export interface DeleteUsersIdData {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface DeleteUsersIdErrors {
  /**
   * User not found
   */
  404: unknown;
}

export interface DeleteUsersIdResponses {
  /**
   * User deleted successfully
   */
  200: {
    id: number;
  };
}

export type DeleteUsersIdResponse = DeleteUsersIdResponses[keyof DeleteUsersIdResponses];

export interface GetUsersByIdData {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface GetUsersByIdErrors {
  /**
   * User not found
   */
  404: unknown;
}

export interface GetUsersByIdResponses {
  /**
   * User Details
   */
  200: {
    id: number;
    name: string;
    jobTitle: string;
  };
}

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export interface PatchUsersIdData {
  body?: {
    name: string;
    jobTitle: string;
  };
  path: {
    id: number;
  };
  query?: never;
  url: '/users/{id}';
}

export interface PatchUsersIdErrors {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * User not found
   */
  404: unknown;
}

export interface PatchUsersIdResponses {
  /**
   * User updated successfully
   */
  200: {
    id: number;
    name: string;
    jobTitle: string;
  };
}

export type PatchUsersIdResponse = PatchUsersIdResponses[keyof PatchUsersIdResponses];
