// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PostAuthLoginData = {
    body?: {
        email: string;
        organisation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Login not authorized
     */
    401: {
        message: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login Successful
     */
    200: {
        message: string;
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type DeleteSessionResponses = {
    /**
     * Session Deleted
     */
    200: {
        message: string;
    };
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type GetSessionResponses = {
    /**
     * Public Session Data
     */
    200: {
        email: string;
        name: string;
        company: string;
        avatar?: {
            src: string;
            alt: string;
        };
    };
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string;
        sort?: string | Array<string>;
    };
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * List of Users
     */
    200: {
        results: Array<{
            id: number;
            name: string;
            jobTitle: string;
        }>;
        count: number;
        page: number;
        next?: string;
        previous?: string;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body?: {
        name: string;
        jobTitle: string;
    };
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type PostUsersResponses = {
    /**
     * User created successfully
     */
    201: {
        id: number;
        name: string;
        jobTitle: string;
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type DeleteUsersIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUsersIdErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type DeleteUsersIdResponses = {
    /**
     * User deleted successfully
     */
    200: {
        id: number;
    };
};

export type DeleteUsersIdResponse = DeleteUsersIdResponses[keyof DeleteUsersIdResponses];

export type GetUsersIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersIdErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type GetUsersIdResponses = {
    /**
     * User Details
     */
    200: {
        id: number;
        name: string;
        jobTitle: string;
    };
};

export type GetUsersIdResponse = GetUsersIdResponses[keyof GetUsersIdResponses];

export type PatchUsersIdData = {
    body?: {
        name: string;
        jobTitle: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type PatchUsersIdErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type PatchUsersIdResponses = {
    /**
     * User updated successfully
     */
    200: {
        id: number;
        name: string;
        jobTitle: string;
    };
};

export type PatchUsersIdResponse = PatchUsersIdResponses[keyof PatchUsersIdResponses];
