// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPostAuthLoginData = z.object({
  body: z.object({
    email: z.string(),
    organisation: z.string(),
  }).optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export type PostAuthLoginDataZodType = z.infer<typeof zPostAuthLoginData>;

/**
 * Login Successful
 */
export const zPostAuthLoginResponse = z.object({
  message: z.string(),
});

export type PostAuthLoginResponseZodType = z.infer<typeof zPostAuthLoginResponse>;

export const zDeleteSessionData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export type DeleteSessionDataZodType = z.infer<typeof zDeleteSessionData>;

/**
 * Session Deleted
 */
export const zDeleteSessionResponse = z.object({
  message: z.string(),
});

export type DeleteSessionResponseZodType = z.infer<typeof zDeleteSessionResponse>;

export const zGetSessionData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export type GetSessionDataZodType = z.infer<typeof zGetSessionData>;

/**
 * Public Session Data
 */
export const zGetSessionResponse = z.object({
  user: z.object({
    email: z.string(),
    name: z.string(),
    company: z.string(),
    avatar: z.object({
      src: z.string(),
      alt: z.string(),
    }).optional(),
  }).optional(),
});

export type GetSessionResponseZodType = z.infer<typeof zGetSessionResponse>;

export const zGetPaginatedUsersData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.object({
    page: z.int().gte(1).lte(9007199254740991).optional(),
    page_size: z.int().gte(5).lte(100).optional(),
    search: z.string().optional(),
    sort: z.union([
      z.string(),
      z.array(z.string()),
    ]).optional(),
  }).optional(),
});

export type GetPaginatedUsersDataZodType = z.infer<typeof zGetPaginatedUsersData>;

/**
 * List of Users
 */
export const zGetPaginatedUsersResponse = z.object({
  results: z.array(z.object({
    id: z.number(),
    name: z.string(),
    jobTitle: z.string(),
  })),
  count: z.number(),
  page: z.number(),
  next: z.url().optional(),
  previous: z.url().optional(),
});

export type GetPaginatedUsersResponseZodType = z.infer<typeof zGetPaginatedUsersResponse>;

export const zPostUsersData = z.object({
  body: z.object({
    name: z.string(),
    jobTitle: z.string(),
  }).optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

export type PostUsersDataZodType = z.infer<typeof zPostUsersData>;

/**
 * User created successfully
 */
export const zPostUsersResponse = z.object({
  id: z.number(),
  name: z.string(),
  jobTitle: z.string(),
});

export type PostUsersResponseZodType = z.infer<typeof zPostUsersResponse>;

export const zDeleteUsersIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.number(),
  }),
  query: z.never().optional(),
});

export type DeleteUsersIdDataZodType = z.infer<typeof zDeleteUsersIdData>;

/**
 * User deleted successfully
 */
export const zDeleteUsersIdResponse = z.object({
  id: z.number(),
});

export type DeleteUsersIdResponseZodType = z.infer<typeof zDeleteUsersIdResponse>;

export const zGetUsersByIdData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.number(),
  }),
  query: z.never().optional(),
});

export type GetUsersByIdDataZodType = z.infer<typeof zGetUsersByIdData>;

/**
 * User Details
 */
export const zGetUsersByIdResponse = z.object({
  id: z.number(),
  name: z.string(),
  jobTitle: z.string(),
});

export type GetUsersByIdResponseZodType = z.infer<typeof zGetUsersByIdResponse>;

export const zPatchUsersIdData = z.object({
  body: z.object({
    name: z.string(),
    jobTitle: z.string(),
  }).optional(),
  path: z.object({
    id: z.number(),
  }),
  query: z.never().optional(),
});

export type PatchUsersIdDataZodType = z.infer<typeof zPatchUsersIdData>;

/**
 * User updated successfully
 */
export const zPatchUsersIdResponse = z.object({
  id: z.number(),
  name: z.string(),
  jobTitle: z.string(),
});

export type PatchUsersIdResponseZodType = z.infer<typeof zPatchUsersIdResponse>;
