---
apiVersion: launchpad.sky.uk/v1alpha1
kind: Gateway
metadata:
  name: hey-api-test-app
spec:
  realms:
    - name: ping
      auth: none
      allowInternet: false
      allowOnPrem: true
      routes:
        - path: / # https://hey-api-test-app.internal.test.adtechplatform.sky.com/
          methods:
            - GET

  services:
    - name: hey-api-test-app
      port: 80
