---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hey-api-test-server
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
        - name: adtech-adf-server
          image: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-stage/hey-api-test/hey-api-test-server:${GIT_TAG}
