// This file is auto-generated by @hey-api/openapi-ts

import type { _JSONValue, UseMutationOptions } from '@pinia/colada';

import type { Options } from '../sdk.gen';
import type { DeleteSessionData, DeleteSessionResponse, DeleteUsersIdData, DeleteUsersIdResponse, GetSessionData, GetSessionResponse, GetUsersData, GetUsersIdData, GetUsersIdResponse, GetUsersResponse, PatchUsersIdData, PatchUsersIdResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostUsersData, PostUsersResponse } from '../types.gen';
import { defineQueryOptions } from '@pinia/colada';
import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { deleteSession, deleteUsersId, getSession, getUsers, getUsersId, patchUsersId, postAuthLogin, postUsers } from '../sdk.gen';

/**
 * Login to the BFF.
 */
export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, Options<PostAuthLoginData>, PostAuthLoginError> => ({
  mutation: async (vars) => {
    const { data } = await postAuthLogin({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete the current user session.
 */
export const deleteSessionMutation = (options?: Partial<Options<DeleteSessionData>>): UseMutationOptions<DeleteSessionResponse, Options<DeleteSessionData>, Error> => ({
  mutation: async (vars) => {
    const { data } = await deleteSession({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'path'> & {
    _id: string;
    baseUrl?: _JSONValue;
    body?: _JSONValue;
    query?: _JSONValue;
    tags?: _JSONValue;
  },
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
  QueryKey<TOptions>[0],
] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (tags) {
    params.tags = tags as unknown as _JSONValue;
  }
  if (options?.body !== undefined) {
    const normalizedBody = serializeQueryKeyValue(options.body);
    if (normalizedBody !== undefined) {
      params.body = normalizedBody;
    }
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query !== undefined) {
    const normalizedQuery = serializeQueryKeyValue(options.query);
    if (normalizedQuery !== undefined) {
      params.query = normalizedQuery;
    }
  }
  return [params];
};

export const getSessionQueryKey = (options?: Options<GetSessionData>) => createQueryKey('getSession', options);

/**
 * Get public session data.
 */
export const getSessionQuery = defineQueryOptions<Options<GetSessionData>, GetSessionResponse, Error>((options?: Options<GetSessionData>) => ({
  key: getSessionQueryKey(options),
  query: async (context) => {
    const { data } = await getSession({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Get list of users
 */
export const getUsersQuery = defineQueryOptions<Options<GetUsersData>, GetUsersResponse, Error>((options?: Options<GetUsersData>) => ({
  key: getUsersQueryKey(options),
  query: async (context) => {
    const { data } = await getUsers({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Create a new user
 */
export const postUsersMutation = (options?: Partial<Options<PostUsersData>>): UseMutationOptions<PostUsersResponse, Options<PostUsersData>, Error> => ({
  mutation: async (vars) => {
    const { data } = await postUsers({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

/**
 * Delete user by ID
 */
export const deleteUsersIdMutation = (options?: Partial<Options<DeleteUsersIdData>>): UseMutationOptions<DeleteUsersIdResponse, Options<DeleteUsersIdData>, Error> => ({
  mutation: async (vars) => {
    const { data } = await deleteUsersId({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});

export const getUsersIdQueryKey = (options: Options<GetUsersIdData>) => createQueryKey('getUsersId', options);

/**
 * Get user by ID
 */
export const getUsersIdQuery = defineQueryOptions<Options<GetUsersIdData>, GetUsersIdResponse, Error>((options: Options<GetUsersIdData>) => ({
  key: getUsersIdQueryKey(options),
  query: async (context) => {
    const { data } = await getUsersId({
      ...options,
      ...context,
      throwOnError: true,
    });
    return data;
  },
}));

/**
 * Update user by ID
 */
export const patchUsersIdMutation = (options?: Partial<Options<PatchUsersIdData>>): UseMutationOptions<PatchUsersIdResponse, Options<PatchUsersIdData>, Error> => ({
  mutation: async (vars) => {
    const { data } = await patchUsersId({
      ...options,
      ...vars,
      throwOnError: true,
    });
    return data;
  },
});
